---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yxy.
--- DateTime: 2022/10/26 12:39
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local stockKey = "hmdp:seckill:stock:" .. voucherId
local orderKey = "hmdp:seckill:order:" .. voucherId


-- 1. 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足
    return 1
end
-- 2. 判断用户是否已经下单
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 重复下单
    return 2
end

-- 3. 扣库存
redis.call('incrby', stockKey, -1)
-- 4. 下单（保存用户）
redis.call('sadd', orderKey, userId)

return 0